"""
Language strings.
"""


TEXT_1 = "  1 - Hardware settings  "
TEXT_2 = "Input device:"
TEXT_3 = "Output device:"
TEXT_4 = "- No devices -"
TEXT_5 = "Test"
TEXT_6 = "Invalid"
TEXT_7 = "  2 - Measurement settings  "
TEXT_8 = "Generated signal"
TEXT_9 = "MLS length [samples]:"
TEXT_10 = "Amplitude (0.0 - 1.0):"
TEXT_11 = "Playback pre-delay [ms]:"
TEXT_12 = "Recorded signal"
TEXT_13 = "Expected decay time [s]:"
TEXT_14 = "Recover default"
TEXT_15 = "Validate numbers"
TEXT_16 = "  3 - Output data  "
TEXT_17 = "Save data to text file:"
TEXT_18 = "..."
TEXT_19 = "Plot measured impulse response."
TEXT_20 = "  4 - Execute measurement  "
TEXT_21 = "START"
TEXT_22 = "Status: Idle."
TEXT_23 = "MSc. Acoustics and Audio Technology, 2015 - Aalborg University"

TEXT_24 = "Sampling rates [Hz]:"
TEXT_25 = "Bit depths [bit]:"
TEXT_26 = "Input channels:"
TEXT_27 = "Output channels:"
TEXT_28 = "Input latency [ms]:"
TEXT_29 = "Output latency [ms]:"

TEXT_30 = "ERROR!"
TEXT_31 = "Please, select where to save the IR to ..."
TEXT_32 = "Select at least one action, saving or plotting."